services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\MetricsExporter\:
    resource: '../Classes/*'

  AUS\MetricsExporter\Service\CollectorService:
    public: true

  AUS\MetricsExporter\EventListener\AlterTableDefinitionStatementsEventListener:
    tags:
      -
        name: event.listener
        identifier: aus/metrics-exporter/alter-table-definition-statements-event-listener
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent