services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\AusMetricsExporter\:
    resource: '../Classes/*'

  AUS\AusMetricsExporter\Command\MetricsCommand:
    tags:
      - name: 'console.command'
        command: 'andersundsehr:metrics-exporter:export'
        description: 'Writes metrics to the configured place where you can scrape them'

  AUS\AusMetricsExporter\Service\CollectorService:
    public: true

