services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\AusMetricsExporter\:
    resource: '../Classes/*'

  AUS\AusMetricsExporter\Service\CollectorService:
    public: true

  AUS\AusMetricsExporter\Exporter\MetricsExporter:
    public: true
